### ISSUE TITLE
cf域名dns管理页面自定义主机名接口报错

### ISSUE THREAD

**Issue by ilay1678** [open-tdp/tdp-cloud#34]
请求：
``` {"Method":"GET","Path":"/zones/*****/custom_hostnames/fallback_origin"}```
响应
```{"Error":{"Message":"Resource not found."}}```

**Comment by rehiy** [comment]
你需要先加一个对应的解析

**Comment by ilay1678** [comment]
感觉现在不太友好，之前没用过这个功能，现在解析页面自定义主机名那一块一直是刷新状态

**Comment by rehiy** [comment]
我刚刚确认了下，自定义主机域名，需要添加权限 `Zone.SSL and Certificates`，是文档里漏了

**Comment by ilay1678** [comment]
这个我添加了的，添加之前报的是未授权

**Comment by rehiy** [comment]
如果遇到交互异常的情况，可以刷新页面看看，目前处于前期开发阶段，可能存在这样的问题。我尽量排查下。

**Comment by rehiy** [comment]
已经重现，计划修复中

**Comment by rehiy** [comment]
感谢分享，bug已修复，明日发版解决。
