### ISSUE TITLE
国际阿里云不能显示具体域名

### ISSUE THREAD

**Issue by WisdomGE-cloud** [open-tdp/tdp-cloud#35]
右上角能显示数量，但是不能显示域名
![QQ浏览器截图20230227171246](https://user-images.githubusercontent.com/62182538/221522080-0ab3aa37-8727-4a38-a05b-79a4f080d1bd.png)

然后就是添加多个账号之后，所有域名混在一起不知道哪个属于哪个账号了。

**Comment by rehiy** [comment]
阿里云各项功能正在开发中，预计本周内开发完成

**Comment by rehiy** [comment]
多账号显示问题也有计划，会显示vendor
