### ISSUE TITLE
解析记录支持升降序排列

### ISSUE THREAD

**Issue by HanadaLee** [open-tdp/tdp-cloud#43]
![image](https://user-images.githubusercontent.com/33758411/222918366-4d184ace-fab1-427b-b820-48399fc694a8.png)
当前UI不支持针对列表某个维度做升序或降序排列，在查找解析记录时比较不便，建议支持一下某列的升降序排列
比如下面cloudflare这种
![image](https://user-images.githubusercontent.com/33758411/222918477-ff0d1d87-9360-4f1e-b794-789eb9489a1d.png)

**Comment by rehiy** [comment]
will do that

**Comment by rehiy** [comment]
enable for next release
