### ISSUE TITLE
cloudflare获取不到任何数据

### ISSUE THREAD

**Issue by saobilin** [open-tdp/tdp-cloud#46]
反复检查api token的权限配置正确 api token正确 邮箱正确 点进去管理都是空白

**Comment by rehiy** [comment]
这里前端界面上的确有个bug，今天上午已定位，晚些时间修复后发布新的二进制文件。

感谢反馈，感谢支持。

**Comment by saobilin** [comment]
谢谢大佬！还有点小问题 手机端有些字排版好像有问题 有些ui感觉怪怪的 大佬有时间的话可以看看 感谢大佬的工作

**Comment by rehiy** [comment]
手机上由于屏幕dpi和放大问题，的确有些不正常，后期我统一调整下

**Comment by saobilin** [comment]
0.9.3 cloudflare管理显示
Invalid request headers

**Comment by rehiy** [comment]
测试未重现，地址栏#号后面的路由贴下贴下看看？

**Comment by saobilin** [comment]
#/vendor/cloudflare/1

**Comment by rehiy** [comment]
OK，我继续排查下

**Comment by rehiy** [comment]
我在测试站上添加了一个授权，是没有问题的。
不过我猜测，可能还是和token有关系，你看看你的touken是不是32位小写的，如果是，你在cf后台roll更换一下看看。

![image](https://user-images.githubusercontent.com/8297757/223943912-82c36e3c-1ecf-4a48-a692-1f47570f93de.png)

**Comment by saobilin** [comment]
官方接入是无法显示的吗
我这边没报错但还是一片空白
token也roll了

**Comment by rehiy** [comment]
项目首页有微信群二维码了，可以扫码进来

**Comment by rehiy** [comment]
一键安装脚本问题，fixed
