### ISSUE TITLE
希望SSH终端->密钥管理处增加用私钥生成公钥的功能

### ISSUE THREAD

**Issue by hapke24** [open-tdp/tdp-cloud#50]
有时只有私钥没有公钥需要自己手动生成才能添加，比较麻烦（虽然公钥那一栏也填私钥也能保存）。

例如宝塔，生成的SSH密钥就只有私钥。

**Comment by rehiy** [comment]
本意是为了帮助记录的，可能还会需要部署到其他服务器，可以暂时填写任意字符绕过验证。我们后期来做个优化
