### ISSUE TITLE
希望能给单独的域名/域名记录加注释

### ISSUE THREAD

**Issue by hapke24** [open-tdp/tdp-cloud#53]
可以拿来备忘，备注一些诸如到期日期、用途之类的信息。

cf有这个给域名记录备注的功能，但是dp貌似没有

![1679323867766](https://user-images.githubusercontent.com/49407099/226378289-67e3f153-b527-4543-a1ed-47e9c73aae8f.png)

**Comment by rehiy** [comment]
#40 将一起实施
