### ISSUE TITLE
提供禁用百度统计的开关

### ISSUE THREAD

**Issue by HanadaLee** [open-tdp/tdp-cloud#59]
![image](https://user-images.githubusercontent.com/33758411/226953056-1ea629c6-b062-47bf-8ad8-c762897b9894.png)
新版本似乎带上了百度统计，而且没找到哪里可以去除这个配置的地方

**Comment by rehiy** [comment]
开发板暂时不准备支持，v1.0 正式版将提供统一的后台开关，如果非常介意可自行编译下。
