### ISSUE TITLE
域名解析记录编辑建议

### ISSUE THREAD

**Issue by hapke24** [open-tdp/tdp-cloud#61]
域名解析页面

希望当鼠标停留在一条记录上时，这条记录会变暗。

因为一行比较长，当想选择某条记录时，容易看走眼选错到隔壁行。

如果这是想删除某条记录，容易删错且无法挽回。

![1680203725389](https://user-images.githubusercontent.com/49407099/228940629-1f2e9888-a86c-4115-aab2-1465e1804bc1.png)

**Comment by rehiy** [comment]
done
